"""Map centroids for story regions and country/city labels (used by coverage / hotspot logic)."""

STORY_REGION_CENTROIDS = {
    "united-states": {"label": "United States", "country": "United States", "admin1": None, "latitude": 39.8283, "longitude": -98.5795},
    "europe": {"label": "Europe", "country": "Europe", "admin1": None, "latitude": 50.1109, "longitude": 14.417},
    "middle-east": {"label": "Middle East", "country": "Middle East", "admin1": None, "latitude": 31.7683, "longitude": 35.2137},
    "eurasia": {"label": "Eurasia", "country": "Eurasia", "admin1": None, "latitude": 48.8566, "longitude": 37.6173},
    "south-asia": {"label": "South Asia", "country": "South Asia", "admin1": None, "latitude": 28.6139, "longitude": 77.209},
    "asia-pacific": {"label": "Asia-Pacific", "country": "Asia-Pacific", "admin1": None, "latitude": 1.3521, "longitude": 103.8198},
    "africa": {"label": "Africa", "country": "Africa", "admin1": None, "latitude": 9.082, "longitude": 8.6753},
    "global": {"label": "Global", "country": "Global", "admin1": None, "latitude": 20.0, "longitude": 0.0},
}
COUNTRY_CENTROIDS = {
    # Country-level fallbacks
    "afghanistan": {"label": "Afghanistan", "country": "Afghanistan", "admin1": None, "latitude": 33.9391, "longitude": 67.71},
    "australia": {"label": "Australia", "country": "Australia", "admin1": None, "latitude": -25.2744, "longitude": 133.7751},
    "brazil": {"label": "Brazil", "country": "Brazil", "admin1": None, "latitude": -14.235, "longitude": -51.9253},
    "canada": {"label": "Canada", "country": "Canada", "admin1": None, "latitude": 56.1304, "longitude": -106.3468},
    "china": {"label": "China", "country": "China", "admin1": None, "latitude": 35.8617, "longitude": 104.1954},
    "egypt": {"label": "Egypt", "country": "Egypt", "admin1": None, "latitude": 26.8206, "longitude": 30.8025},
    "ethiopia": {"label": "Ethiopia", "country": "Ethiopia", "admin1": None, "latitude": 9.145, "longitude": 40.4897},
    "france": {"label": "France", "country": "France", "admin1": None, "latitude": 46.2276, "longitude": 2.2137},
    "germany": {"label": "Germany", "country": "Germany", "admin1": None, "latitude": 51.1657, "longitude": 10.4515},
    "india": {"label": "India", "country": "India", "admin1": None, "latitude": 20.5937, "longitude": 78.9629},
    "indonesia": {"label": "Indonesia", "country": "Indonesia", "admin1": None, "latitude": -0.7893, "longitude": 113.9213},
    "iran": {"label": "Iran", "country": "Iran", "admin1": None, "latitude": 32.4279, "longitude": 53.688},
    "iraq": {"label": "Iraq", "country": "Iraq", "admin1": None, "latitude": 33.2232, "longitude": 43.6793},
    "israel": {"label": "Israel", "country": "Israel", "admin1": None, "latitude": 31.0461, "longitude": 34.8516},
    "italy": {"label": "Italy", "country": "Italy", "admin1": None, "latitude": 41.8719, "longitude": 12.5674},
    "japan": {"label": "Japan", "country": "Japan", "admin1": None, "latitude": 36.2048, "longitude": 138.2529},
    "jordan": {"label": "Jordan", "country": "Jordan", "admin1": None, "latitude": 30.5852, "longitude": 36.2384},
    "lebanon": {"label": "Lebanon", "country": "Lebanon", "admin1": None, "latitude": 33.8547, "longitude": 35.8623},
    "libya": {"label": "Libya", "country": "Libya", "admin1": None, "latitude": 26.3351, "longitude": 17.2283},
    "mexico": {"label": "Mexico", "country": "Mexico", "admin1": None, "latitude": 23.6345, "longitude": -102.5528},
    "myanmar": {"label": "Myanmar", "country": "Myanmar", "admin1": None, "latitude": 21.9162, "longitude": 95.956},
    "nigeria": {"label": "Nigeria", "country": "Nigeria", "admin1": None, "latitude": 9.082, "longitude": 8.6753},
    "north korea": {"label": "North Korea", "country": "North Korea", "admin1": None, "latitude": 40.3399, "longitude": 127.5101},
    "pakistan": {"label": "Pakistan", "country": "Pakistan", "admin1": None, "latitude": 30.3753, "longitude": 69.3451},
    "palestine": {"label": "Palestine", "country": "Palestine", "admin1": None, "latitude": 31.9522, "longitude": 35.2332},
    "philippines": {"label": "Philippines", "country": "Philippines", "admin1": None, "latitude": 12.8797, "longitude": 121.774},
    "poland": {"label": "Poland", "country": "Poland", "admin1": None, "latitude": 51.9194, "longitude": 19.1451},
    "russia": {"label": "Russia", "country": "Russia", "admin1": None, "latitude": 61.524, "longitude": 105.3188},
    "saudi arabia": {"label": "Saudi Arabia", "country": "Saudi Arabia", "admin1": None, "latitude": 23.8859, "longitude": 45.0792},
    "south africa": {"label": "South Africa", "country": "South Africa", "admin1": None, "latitude": -30.5595, "longitude": 22.9375},
    "south korea": {"label": "South Korea", "country": "South Korea", "admin1": None, "latitude": 35.9078, "longitude": 127.7669},
    "sudan": {"label": "Sudan", "country": "Sudan", "admin1": None, "latitude": 12.8628, "longitude": 30.2176},
    "syria": {"label": "Syria", "country": "Syria", "admin1": None, "latitude": 34.8021, "longitude": 38.9968},
    "taiwan": {"label": "Taiwan", "country": "Taiwan", "admin1": None, "latitude": 23.6978, "longitude": 120.9605},
    "turkey": {"label": "Turkey", "country": "Turkey", "admin1": None, "latitude": 38.9637, "longitude": 35.2433},
    "turkiye": {"label": "Turkey", "country": "Turkey", "admin1": None, "latitude": 38.9637, "longitude": 35.2433},
    "uae": {"label": "United Arab Emirates", "country": "United Arab Emirates", "admin1": None, "latitude": 23.4241, "longitude": 53.8478},
    "uk": {"label": "United Kingdom", "country": "United Kingdom", "admin1": None, "latitude": 55.3781, "longitude": -3.436},
    "ukraine": {"label": "Ukraine", "country": "Ukraine", "admin1": None, "latitude": 48.3794, "longitude": 31.1656},
    "united arab emirates": {"label": "United Arab Emirates", "country": "United Arab Emirates", "admin1": None, "latitude": 23.4241, "longitude": 53.8478},
    "united kingdom": {"label": "United Kingdom", "country": "United Kingdom", "admin1": None, "latitude": 55.3781, "longitude": -3.436},
    "united states": {"label": "United States", "country": "United States", "admin1": None, "latitude": 39.8283, "longitude": -98.5795},
    "us": {"label": "United States", "country": "United States", "admin1": None, "latitude": 39.8283, "longitude": -98.5795},
    "venezuela": {"label": "Venezuela", "country": "Venezuela", "admin1": None, "latitude": 6.4238, "longitude": -66.5897},
    "yemen": {"label": "Yemen", "country": "Yemen", "admin1": None, "latitude": 15.5527, "longitude": 48.5164},
    # City-level entries — conflict zones and major news capitals
    "gaza city": {"label": "Gaza City", "country": "Palestine", "admin1": "Gaza Strip", "latitude": 31.5, "longitude": 34.4667},
    "gaza": {"label": "Gaza City", "country": "Palestine", "admin1": "Gaza Strip", "latitude": 31.5, "longitude": 34.4667},
    "rafah": {"label": "Rafah", "country": "Palestine", "admin1": "Gaza Strip", "latitude": 31.2853, "longitude": 34.2543},
    "khan yunis": {"label": "Khan Yunis", "country": "Palestine", "admin1": "Gaza Strip", "latitude": 31.3461, "longitude": 34.3059},
    "khan younis": {"label": "Khan Yunis", "country": "Palestine", "admin1": "Gaza Strip", "latitude": 31.3461, "longitude": 34.3059},
    "west bank": {"label": "West Bank", "country": "Palestine", "admin1": None, "latitude": 31.9, "longitude": 35.2},
    "ramallah": {"label": "Ramallah", "country": "Palestine", "admin1": "West Bank", "latitude": 31.9038, "longitude": 35.2034},
    "jerusalem": {"label": "Jerusalem", "country": "Israel", "admin1": None, "latitude": 31.7683, "longitude": 35.2137},
    "tel aviv": {"label": "Tel Aviv", "country": "Israel", "admin1": None, "latitude": 32.0853, "longitude": 34.7818},
    "beirut": {"label": "Beirut", "country": "Lebanon", "admin1": None, "latitude": 33.8938, "longitude": 35.5018},
    "southern lebanon": {"label": "Southern Lebanon", "country": "Lebanon", "admin1": "South Governorate", "latitude": 33.27, "longitude": 35.38},
    "tehran": {"label": "Tehran", "country": "Iran", "admin1": None, "latitude": 35.6892, "longitude": 51.389},
    "baghdad": {"label": "Baghdad", "country": "Iraq", "admin1": None, "latitude": 33.3152, "longitude": 44.3661},
    "mosul": {"label": "Mosul", "country": "Iraq", "admin1": "Nineveh", "latitude": 36.335, "longitude": 43.1189},
    "erbil": {"label": "Erbil", "country": "Iraq", "admin1": "Kurdistan Region", "latitude": 36.1901, "longitude": 44.0091},
    "damascus": {"label": "Damascus", "country": "Syria", "admin1": None, "latitude": 33.5138, "longitude": 36.2765},
    "aleppo": {"label": "Aleppo", "country": "Syria", "admin1": "Aleppo Governorate", "latitude": 36.2021, "longitude": 37.1343},
    "idlib": {"label": "Idlib", "country": "Syria", "admin1": "Idlib Governorate", "latitude": 35.9306, "longitude": 36.6339},
    "raqqa": {"label": "Raqqa", "country": "Syria", "admin1": "Raqqa Governorate", "latitude": 35.9524, "longitude": 39.0165},
    "deir ez-zor": {"label": "Deir ez-Zor", "country": "Syria", "admin1": "Deir ez-Zor Governorate", "latitude": 35.3356, "longitude": 40.1418},
    "sanaa": {"label": "Sanaa", "country": "Yemen", "admin1": None, "latitude": 15.3694, "longitude": 44.191},
    "aden": {"label": "Aden", "country": "Yemen", "admin1": None, "latitude": 12.7797, "longitude": 45.0362},
    "hodeidah": {"label": "Hodeidah", "country": "Yemen", "admin1": None, "latitude": 14.7978, "longitude": 42.9554},
    "marib": {"label": "Marib", "country": "Yemen", "admin1": "Marib Governorate", "latitude": 15.4686, "longitude": 45.3247},
    "riyadh": {"label": "Riyadh", "country": "Saudi Arabia", "admin1": None, "latitude": 24.6877, "longitude": 46.7219},
    "amman": {"label": "Amman", "country": "Jordan", "admin1": None, "latitude": 31.9539, "longitude": 35.9106},
    "doha": {"label": "Doha", "country": "Qatar", "admin1": None, "latitude": 25.2854, "longitude": 51.531},
    "dubai": {"label": "Dubai", "country": "United Arab Emirates", "admin1": None, "latitude": 25.2048, "longitude": 55.2708},
    "abu dhabi": {"label": "Abu Dhabi", "country": "United Arab Emirates", "admin1": None, "latitude": 24.4539, "longitude": 54.3773},
    "cairo": {"label": "Cairo", "country": "Egypt", "admin1": None, "latitude": 30.0444, "longitude": 31.2357},
    "tripoli": {"label": "Tripoli", "country": "Libya", "admin1": None, "latitude": 32.8872, "longitude": 13.1913},
    "benghazi": {"label": "Benghazi", "country": "Libya", "admin1": None, "latitude": 32.1196, "longitude": 20.0868},
    "kabul": {"label": "Kabul", "country": "Afghanistan", "admin1": None, "latitude": 34.5553, "longitude": 69.2075},
    "kandahar": {"label": "Kandahar", "country": "Afghanistan", "admin1": "Kandahar Province", "latitude": 31.613, "longitude": 65.7372},
    "kyiv": {"label": "Kyiv", "country": "Ukraine", "admin1": "Kyiv Oblast", "latitude": 50.4501, "longitude": 30.5234},
    "kiev": {"label": "Kyiv", "country": "Ukraine", "admin1": "Kyiv Oblast", "latitude": 50.4501, "longitude": 30.5234},
    "kharkiv": {"label": "Kharkiv", "country": "Ukraine", "admin1": "Kharkiv Oblast", "latitude": 49.9935, "longitude": 36.2304},
    "kherson": {"label": "Kherson", "country": "Ukraine", "admin1": "Kherson Oblast", "latitude": 46.6354, "longitude": 32.6169},
    "zaporizhzhia": {"label": "Zaporizhzhia", "country": "Ukraine", "admin1": "Zaporizhzhia Oblast", "latitude": 47.8388, "longitude": 35.1396},
    "mariupol": {"label": "Mariupol", "country": "Ukraine", "admin1": "Donetsk Oblast", "latitude": 47.0951, "longitude": 37.5426},
    "bakhmut": {"label": "Bakhmut", "country": "Ukraine", "admin1": "Donetsk Oblast", "latitude": 48.5951, "longitude": 37.9956},
    "donetsk": {"label": "Donetsk", "country": "Ukraine", "admin1": "Donetsk Oblast", "latitude": 48.0159, "longitude": 37.8028},
    "luhansk": {"label": "Luhansk", "country": "Ukraine", "admin1": "Luhansk Oblast", "latitude": 48.5676, "longitude": 39.3367},
    "donbas": {"label": "Donbas", "country": "Ukraine", "admin1": "Donetsk Oblast", "latitude": 47.8, "longitude": 38.0},
    "odessa": {"label": "Odessa", "country": "Ukraine", "admin1": "Odessa Oblast", "latitude": 46.4825, "longitude": 30.7233},
    "odesa": {"label": "Odessa", "country": "Ukraine", "admin1": "Odessa Oblast", "latitude": 46.4825, "longitude": 30.7233},
    "crimea": {"label": "Crimea", "country": "Ukraine", "admin1": "Autonomous Republic of Crimea", "latitude": 45.3354, "longitude": 34.1048},
    "moscow": {"label": "Moscow", "country": "Russia", "admin1": None, "latitude": 55.7558, "longitude": 37.6176},
    "st. petersburg": {"label": "St. Petersburg", "country": "Russia", "admin1": None, "latitude": 59.9311, "longitude": 30.3609},
    "saint petersburg": {"label": "St. Petersburg", "country": "Russia", "admin1": None, "latitude": 59.9311, "longitude": 30.3609},
    "minsk": {"label": "Minsk", "country": "Belarus", "admin1": None, "latitude": 53.9045, "longitude": 27.5615},
    "tbilisi": {"label": "Tbilisi", "country": "Georgia", "admin1": None, "latitude": 41.6938, "longitude": 44.8015},
    "yerevan": {"label": "Yerevan", "country": "Armenia", "admin1": None, "latitude": 40.1792, "longitude": 44.499},
    "baku": {"label": "Baku", "country": "Azerbaijan", "admin1": None, "latitude": 40.4093, "longitude": 49.8671},
    "nagorno-karabakh": {"label": "Nagorno-Karabakh", "country": "Azerbaijan", "admin1": None, "latitude": 40.0, "longitude": 46.75},
    "london": {"label": "London", "country": "United Kingdom", "admin1": "England", "latitude": 51.5074, "longitude": -0.1278},
    "paris": {"label": "Paris", "country": "France", "admin1": None, "latitude": 48.8566, "longitude": 2.3522},
    "berlin": {"label": "Berlin", "country": "Germany", "admin1": None, "latitude": 52.52, "longitude": 13.405},
    "brussels": {"label": "Brussels", "country": "Belgium", "admin1": None, "latitude": 50.8503, "longitude": 4.3517},
    "warsaw": {"label": "Warsaw", "country": "Poland", "admin1": None, "latitude": 52.2297, "longitude": 21.0122},
    "belgrade": {"label": "Belgrade", "country": "Serbia", "admin1": None, "latitude": 44.7866, "longitude": 20.4489},
    "pristina": {"label": "Pristina", "country": "Kosovo", "admin1": None, "latitude": 42.6629, "longitude": 21.1655},
    "beijing": {"label": "Beijing", "country": "China", "admin1": None, "latitude": 39.9042, "longitude": 116.4074},
    "shanghai": {"label": "Shanghai", "country": "China", "admin1": None, "latitude": 31.2304, "longitude": 121.4737},
    "hong kong": {"label": "Hong Kong", "country": "China", "admin1": "Hong Kong SAR", "latitude": 22.3193, "longitude": 114.1694},
    "taipei": {"label": "Taipei", "country": "Taiwan", "admin1": None, "latitude": 25.033, "longitude": 121.5654},
    "south china sea": {"label": "South China Sea", "country": "International Waters", "admin1": None, "latitude": 14.0, "longitude": 113.0},
    "taiwan strait": {"label": "Taiwan Strait", "country": "International Waters", "admin1": None, "latitude": 24.5, "longitude": 120.0},
    "seoul": {"label": "Seoul", "country": "South Korea", "admin1": None, "latitude": 37.5665, "longitude": 126.978},
    "pyongyang": {"label": "Pyongyang", "country": "North Korea", "admin1": None, "latitude": 39.0392, "longitude": 125.7625},
    "tokyo": {"label": "Tokyo", "country": "Japan", "admin1": None, "latitude": 35.6762, "longitude": 139.6503},
    "new delhi": {"label": "New Delhi", "country": "India", "admin1": None, "latitude": 28.6139, "longitude": 77.209},
    "delhi": {"label": "New Delhi", "country": "India", "admin1": None, "latitude": 28.6139, "longitude": 77.209},
    "mumbai": {"label": "Mumbai", "country": "India", "admin1": "Maharashtra", "latitude": 19.076, "longitude": 72.8777},
    "kashmir": {"label": "Kashmir", "country": "India", "admin1": "Jammu and Kashmir", "latitude": 34.0, "longitude": 76.0},
    "islamabad": {"label": "Islamabad", "country": "Pakistan", "admin1": None, "latitude": 33.6844, "longitude": 73.0479},
    "karachi": {"label": "Karachi", "country": "Pakistan", "admin1": "Sindh", "latitude": 24.8607, "longitude": 67.0011},
    "lahore": {"label": "Lahore", "country": "Pakistan", "admin1": "Punjab", "latitude": 31.5204, "longitude": 74.3587},
    "dhaka": {"label": "Dhaka", "country": "Bangladesh", "admin1": None, "latitude": 23.8103, "longitude": 90.4125},
    "yangon": {"label": "Yangon", "country": "Myanmar", "admin1": None, "latitude": 16.8409, "longitude": 96.1735},
    "naypyidaw": {"label": "Naypyidaw", "country": "Myanmar", "admin1": None, "latitude": 19.7633, "longitude": 96.0785},
    "khartoum": {"label": "Khartoum", "country": "Sudan", "admin1": None, "latitude": 15.5007, "longitude": 32.5599},
    "port sudan": {"label": "Port Sudan", "country": "Sudan", "admin1": "Red Sea State", "latitude": 19.6158, "longitude": 37.2164},
    "addis ababa": {"label": "Addis Ababa", "country": "Ethiopia", "admin1": None, "latitude": 9.0054, "longitude": 38.7636},
    "tigray": {"label": "Tigray", "country": "Ethiopia", "admin1": "Tigray Region", "latitude": 14.0, "longitude": 38.5},
    "nairobi": {"label": "Nairobi", "country": "Kenya", "admin1": None, "latitude": -1.2921, "longitude": 36.8219},
    "mogadishu": {"label": "Mogadishu", "country": "Somalia", "admin1": "Banadir", "latitude": 2.0469, "longitude": 45.3182},
    "juba": {"label": "Juba", "country": "South Sudan", "admin1": "Central Equatoria", "latitude": 4.8517, "longitude": 31.5825},
    "lagos": {"label": "Lagos", "country": "Nigeria", "admin1": "Lagos State", "latitude": 6.5244, "longitude": 3.3792},
    "abuja": {"label": "Abuja", "country": "Nigeria", "admin1": "FCT", "latitude": 9.0765, "longitude": 7.3986},
    "bamako": {"label": "Bamako", "country": "Mali", "admin1": None, "latitude": 12.6392, "longitude": -8.0029},
    "ouagadougou": {"label": "Ouagadougou", "country": "Burkina Faso", "admin1": None, "latitude": 12.3647, "longitude": -1.5353},
    "niamey": {"label": "Niamey", "country": "Niger", "admin1": None, "latitude": 13.5137, "longitude": 2.1098},
    "washington": {"label": "Washington, DC", "country": "United States", "admin1": "District of Columbia", "latitude": 38.9072, "longitude": -77.0369},
    "washington dc": {"label": "Washington, DC", "country": "United States", "admin1": "District of Columbia", "latitude": 38.9072, "longitude": -77.0369},
    "new york": {"label": "New York", "country": "United States", "admin1": "New York", "latitude": 40.7128, "longitude": -74.006},
    "havana": {"label": "Havana", "country": "Cuba", "admin1": None, "latitude": 23.1136, "longitude": -82.3666},
    "caracas": {"label": "Caracas", "country": "Venezuela", "admin1": None, "latitude": 10.4806, "longitude": -66.9036},
}
